Beta
adamkulig/recipes-search-engine-react-redux pull request #1
Opened 2018-06-12 22:02 UTC by adamkulig

2018-06-12 23:14 UTC, yuriyyakym requested changes

2018-06-12 23:14 UTC, yuriyyakym commented on src/api/fetch.js
> +  }));
Strange lisp-style formatting. Put closing bracket on new line.

2018-06-12 23:14 UTC, yuriyyakym commented on src/api/fetch.js
> +const recipeSelectedInfo = (json) => json.hits.map(
This name doesn't sound like a function name.

2018-06-12 23:14 UTC, yuriyyakym commented on src/components/Anchor/Anchor.js
> +        target='_blank'>
It's a common component. Should each link on the page navigate to new tab? Maybe it should be configurable?

2018-06-12 23:14 UTC, yuriyyakym commented on src/components/Modal/Modal.scss
> +}
missing newline

2018-06-12 23:14 UTC, yuriyyakym commented on src/components/Spinner/Spinner.js
> +)
missing semicolon

2018-06-12 23:14 UTC, yuriyyakym commented on src/components/Modal/Modal.js
> +)
missing semicolon

2018-06-12 23:14 UTC, yuriyyakym commented on src/components/Spinner/Spinner.scss
> +}
missing newline

2018-06-12 23:14 UTC, yuriyyakym commented on src/index.js
> +const devTools = window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
missing semicolon

2018-06-12 23:14 UTC, yuriyyakym commented on src/index.js
> +import './index.scss';
I'd suggest keeping styles import below js imports

2018-06-12 23:14 UTC, yuriyyakym commented on src/index.scss
> +    )
Wrong indent?

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/FavoriteList/FavoriteList.js
> +import './FavoriteList.scss';
redundant styles import?

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/FavoriteList/FavoriteList.js
> +          <Recipe key={index} item={item}/>
Does item has it's id? If yes, it would be great to use this id as a key.

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/Footer/Footer.js
> +  )
missing semicolon

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/Header/Header.js
> +  )
missing semicolon

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/MainContent/MainContent.js
> +        { loading &&
Strange formatting. I'd suggest wrapping jsx in round brackets

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/MainContent/MainContent.js
> +            <Recipe key={index} index={index} item={item}/>
same as above

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/MainContent/MainContent.js
> +export default connect(mapStateToProps, null)(MainContent);
redundant second parameter passed to connect function

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/MainContent/Search/Search.js
> +  ingredients = (event) => {
It doesn't sound like a function name. Use some verb.

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/MainContent/Search/Search.js
> +          onKeyUp={this.enterClicked}
it's not `enterClicked` because it's fired on each keyUp, so function name is wrong.

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/MainContent/Search/Search.js
> +  kcal = (event) => {
It doesn't sound like a function name. Use some verb.

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/MainContent/Search/Search.js
> +          placeholder='beef,onions,beans'
missing spaces in placeholder text

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/Nav/Nav.js
> +import { IoIosStar, IoIosSearchStrong } from 'react-icons/lib/io'
missing semicolon

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/Recipe/Recipe.js
> +  }
missing semicolon

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/Recipe/Recipe.js
> +    ? onRemoveFromFavorite(recipe)
wrong indent?

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/Recipe/Recipe.js
> +          className={classNames('recipe', isEvenRecipe && 'recipe--even')}
redundant `isEvenRecipe` variable and 'recipe--even' className. You can use css nth-child selector, but it's up to you

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/Recipe/Recipe.js
> +  const recipe = this.props.item;
wrong indent

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/RecipeDetails/RecipeDetails.js
> +    recipe = recipes.find(item => item.id === Number(recipeId));
this can be assigned right in declaration (previous line)

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/RecipeDetails/RecipeDetails.js
> +              className={classNames('recipe-details__ingredients__item', (index % 2 === 0) && 'recipe-details__ingredients__item--even')}
same as above

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/RecipeDetails/RecipeDetails.js
> +}
missing semicolon

2018-06-12 23:14 UTC, yuriyyakym commented on src/modules/RecipeDetails/RecipeDetails.scss
> +
redundant newline

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/actions/recipes.js
> +      .catch(error => dispatch(saveRecipesFail(error)))
missing semicolon

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/actions/recipes.js
> +    const kcalFilled = (kcal.length > 0 ) && `&calories=${kcal}`;
1) reundant brackets
2) redundant space after `0`

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/actions/recipes.js
> +    const url = `https://api.edamam.com/search?app_id=${APP_ID}&app_key=${APP_KEY}&q=${ingredients}&${kcalFilled}`;
Wrong url, you have `&${kcalFilled}` kcalFilled can be undefined or string with `&`, so result url will look like `q=ingredient1&&10` (should be 1 amp)

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/reducers/favoritesReducer.js
> +        )
missing semicolon

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/reducers/favoritesReducer.js
> +      state.map(item => {
you should use `some` function here

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/reducers/favoritesReducer.js
> +      state.map(item => {
you will check whether recipe is already in your favorites, if yes - return state, and update state otherwise

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/reducers/favoritesReducer.js
> +      return state = state.filter(item => !(
do not assign anything to state variable

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/reducers/favoritesReducer.js
> +      return state = state.filter(item => !(
You state is an array here, so just return filtered array

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/reducers/fetchingRecipesReducer.js
> +const initialState = [{
You initialState structure does not correspond to reducer model. You return an object from reducer, and here you have an array of objects.

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/reducers/index.js
> +  fetchingRecipes: fetchingRecipesReducer
This reducer seems to be redundant. If you want to keep an information about `loading` you can keep it in `recipesReducer`

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/reducers/recipesReducer.js
> +          id: getId(),
Generally it's not the best approach, since reducers should be pure functions and this line makes it non-pure.

2018-06-12 23:14 UTC, yuriyyakym commented on src/state/reducers/recipesReducer.js
> +          id: getId(),
But if id is not returned by backend, just leave it as is

2018-06-13 08:39 UTC, adamkulig commented on src/modules/Recipe/Recipe.js
> +          className={classNames('recipe', isEvenRecipe && 'recipe--even')}
I tried like that but it doesn't work

2018-06-14 05:09 UTC, merged